# Generated by Django 4.0.2 on 2022-02-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=None, max_length=8, verbose_name='name'),
        ),
    ]
